-- 
ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- sqlplus /nolog
-- connect / as sysdba
-- @?\sqlplus\admin\plustrce.sql
-- GRANT PLUSTRACE TO SCOTT;
-- GRANT DBA TO SCOTT;

CREATE TABLE emp0 AS SELECT * FROM emp;

DROP TABLE EMP1;

CREATE TABLE emp1 AS SELECT * FROM EMP;

INSERT INTO EMP1 SELECT * FROM EMP1;
INSERT INTO EMP1 SELECT * FROM EMP1;
INSERT INTO EMP1 SELECT * FROM EMP1;
INSERT INTO EMP1 SELECT * FROM EMP1;
INSERT INTO EMP1 SELECT * FROM EMP1;

UPDATE EMP1 SET EMPNO = ROWNUM;

COMMIT;



